# Generated by Django 4.1.3 on 2022-11-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='image',
            field=models.CharField(default='none', max_length=250),
            preserve_default=False,
        ),
    ]
